### ISSUE TITLE
problem with setting up enviroment

### ISSUE THREAD

**Issue by wz7475** [HongWuL/sAMPpred-GAT#3]
python 3.7 provided by [miniforge conda](https://github.com/conda-forge/miniforge) on x86_64 Ubuntu 20.04.6 LTS

installation via readme
```shell
# commands from readme  
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113  
  
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric==1.7.2 -f https://data.pyg.org/whl/torch-1.11.0+cu113.html  
  
conda install -c conda-forge -c bioconda hhsuite==3.3.0  
  
python test.py  
Traceback (most recent call last):  
  File "test.py", line 3, in <module>  
    from torch_geometric.data import DataLoader  
  File "/home/wzarzecki/miniforge3/envs/gat/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>  
    import torch_geometric.data  
  File "/home/wzarzecki/miniforge3/envs/gat/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>  
    from .data import Data  
  File "/home/wzarzecki/miniforge3/envs/gat/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>  
    from torch_sparse import coalesce, SparseTensor  
  File "/home/wzarzecki/miniforge3/envs/gat/lib/python3.7/site-packages/torch_sparse/__init__.py", line 40, in <module>  
    from .tensor import SparseTensor  # noqa  
  File "/home/wzarzecki/miniforge3/envs/gat/lib/python3.7/site-packages/torch_sparse/tensor.py", line 13, in <module>  
    class SparseTensor(object):  
  File "/home/wzarzecki/miniforge3/envs/gat/lib/python3.7/site-packages/torch/jit/_script.py", line 1302, in script  
    _compile_and_register_class(obj, _rcb, qualified_name)  
  File "/home/wzarzecki/miniforge3/envs/gat/lib/python3.7/site-packages/torch/jit/_recursive.py", line 44, in _compile_and_register_class  
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)  
RuntimeError:  
object has no attribute sparse_csc_tensor:  
  File "/home/wzarzecki/miniforge3/envs/gat/lib/python3.7/site-packages/torch_sparse/tensor.py", line 520  
            value = torch.ones(self.nnz(), dtype=dtype, device=self.device())  
  
        return torch.sparse_csc_tensor(colptr, row, value, self.sizes())  
               ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```
*environment build and package installation took over 10min - building wheels for torch sparse/scatter/cluster*

As an alternative method I tried installation of torch-geometric from conda packages - [torch geometrics](https://anaconda.org/conda-forge/pytorch_geometric)  or [pyg](https://anaconda.org/pyg/pyg)- version 1.7 is not available 

Moreover I failed at sequential installation of packages via pip as specified in Requirements in readme starting from torch-geometric 1.7.2

**Comment by NancyBlack6** [comment]
http://bliulab.net/sAMPpred-GAT/static/download/nrdb90.tar.gz. this link can not be found, is there any other ways to get this database?

**Comment by HongWuL** [comment]
> http://bliulab.net/sAMPpred-GAT/static/download/nrdb90.tar.gz. this link can not be found, is there any other ways to get this database?

Contact [kyan@bliulab.net](mailto:kyan@bliulab.net) to obtain the nrdb90 and NR
